//go:build protodeps

// This file is never built. It exists so `go mod tidy` keeps the modules the
// generated protobuf code needs.
//
// `gen/` is gitignored and regenerated by `make proto` (ADR-0013 defers the
// commit-or-generate decision to Phase 2). On a clean clone the generated
// imports are therefore absent, and a `go mod tidy` run before `make proto`
// would drop grpc and protobuf from go.mod — after which `make proto` produces
// code that does not compile, for a reason nothing on screen explains.
//
// `go mod tidy` considers imports under every build constraint, so the blank
// imports below survive it. Delete this file only when the generated code is
// committed.
package berean

import (
	_ "google.golang.org/grpc"
	_ "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/runtime/protoimpl"
)
